/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * KyawKyar API
 * API documentation for KyawKyar server
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { mutator } from './mutator';
export type Status = typeof Status[keyof typeof Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
  Sold: 'Sold',
  Available: 'Available',
} as const;

export type Fuel = typeof Fuel[keyof typeof Fuel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Fuel = {
  Petrol: 'Petrol',
  Diesel: 'Diesel',
  Electric: 'Electric',
  Hybrid: 'Hybrid',
} as const;

export type Transmission = typeof Transmission[keyof typeof Transmission];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Transmission = {
  Manual: 'Manual',
  Automatic: 'Automatic',
  CVT: 'CVT',
} as const;

export type Visibility = typeof Visibility[keyof typeof Visibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Visibility = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
} as const;

export interface Brand {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

export interface Model {
  id: string;
  name: string;
  brandId: string;
  brand?: Brand;
  createdAt: string;
  updatedAt: string;
}

export interface Region {
  id: string;
  name: string;
  code: string;
}

export interface Color {
  id: string;
  name: string;
}

export interface License {
  id: string;
  carId: string;
  prefixNumber: number;
  prefixLetter: string;
  registrationNumber: number;
  registeredName: string;
  issuedDate: string;
  /** @nullable */
  expiryDate?: string | null;
  regionId: string;
  region?: Region;
  createdAt: string;
  updatedAt: string;
}

export interface ShowroomPhone {
  id: string;
  showroomId: string;
  phone: string;
  /** @nullable */
  label?: string | null;
}

export interface Showroom {
  id: string;
  addressMm: string;
  addressEn: string;
  city: string;
  createdAt: string;
  updatedAt: string;
}

export interface CarImage {
  id: string;
  carId: string;
  isPrimary: boolean;
  sequenceNumber: number;
  visibility: Visibility;
  storageBaseKey: string;
  mimeType: string;
  /** @nullable */
  altText?: string | null;
  /**
   * Public URL for the main image size
   * @nullable
   */
  urlMain?: string | null;
  /**
   * Public URL for the thumbnail image
   * @nullable
   */
  urlThumb?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface PrimaryImage {
  id?: string;
  url?: string;
  isPrimary?: boolean;
  sequenceNumber?: number;
  mimeType?: string;
}

export interface Car {
  id: string;
  modelId: string;
  model?: Model;
  modelYear: number;
  price: number;
  mileage: number;
  fuel: Fuel;
  transmission: Transmission;
  status: Status;
  /** @nullable */
  license?: License;
  colorId: string;
  color?: Color;
  /** @nullable */
  showroomId?: string | null;
  /** @nullable */
  showroom?: Showroom;
  images: CarImage[];
  createdAt: string;
  updatedAt: string;
}

export interface CarListItem {
  id: string;
  modelId: string;
  model?: Model;
  modelYear: number;
  price: number;
  mileage: number;
  fuel: Fuel;
  transmission: Transmission;
  status: Status;
  /** @nullable */
  license?: License;
  colorId: string;
  color?: Color;
  /** @nullable */
  showroomId?: string | null;
  /** @nullable */
  showroom?: Showroom;
  /** @nullable */
  primaryImage?: PrimaryImage;
  createdAt: string;
  updatedAt: string;
}

export interface CarCreate {
  modelId: string;
  modelYear: number;
  price: number;
  mileage: number;
  fuel: Fuel;
  transmission: Transmission;
  status?: Status;
  colorId: string;
  /** @nullable */
  showroomId?: string | null;
}

export interface CarUpdate {
  id?: string;
  modelYear?: number;
  price?: number;
  mileage?: number;
  fuel?: Fuel;
  transmission?: Transmission;
  status?: Status;
  colorId?: string;
  /** @nullable */
  showroomId?: string | null;
}

export interface BrandCreate {
  name: string;
}

export interface ModelCreate {
  name: string;
  brandId: string;
}

export interface CarBatchItem {
  rowIndex: number;
  modelId?: string;
  modelYear?: number;
  price?: number;
  mileage?: number;
  fuel?: Fuel;
  transmission?: Transmission;
  status?: Status;
  colorId?: string;
  /** @nullable */
  showroomId?: string | null;
}

export interface CarsCreateBatch {
  /**
   * @minItems 1
   * @maxItems 50
   */
  cars: CarBatchItem[];
}

/**
 * @nullable
 */
export type CarBatchResultItemErrorMeta = { [key: string]: unknown } | null;

/**
 * @nullable
 */
export type CarBatchResultItemError = {
  message?: string;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  meta?: CarBatchResultItemErrorMeta;
} | null;

export interface CarBatchResultItem {
  rowIndex: number;
  success: boolean;
  /** @nullable */
  car?: Car;
  /** @nullable */
  error?: CarBatchResultItemError;
}

export interface CarsCreateBatchResponse {
  createdCount: number;
  results: CarBatchResultItem[];
}

export type GetApiBrandsParams = {
page?: number;
limit?: number;
};

export type GetApiBrands200 = {
  items?: Brand[];
  total?: number;
  page?: number;
  limit?: number;
};

export type DeleteApiBrandsId200 = {
  deleted?: boolean;
};

export type PostApiCarImagesCarIdUploadBody = {
  images?: Blob[];
  /** Index of the uploaded file (0-based) to mark as primary */
  primaryIndex?: number;
};

export type PostApiCarImagesCarIdUpload201 = {
  message?: string;
};

export type DeleteApiCarImagesImageId200S3Result = { [key: string]: unknown };

export type DeleteApiCarImagesImageId200 = {
  deletedId?: string;
  storageBaseKey?: string;
  s3Result?: DeleteApiCarImagesImageId200S3Result;
};

export type PatchApiCarImagesImageIdSetPrimary200 = {
  setPrimary?: string;
};

export type PatchApiCarImagesImageIdReplaceBody = {
  image?: Blob;
};

export type PatchApiCarImagesImageIdReplace200 = {
  replaced?: string;
  newBaseKey?: string;
};

export type GetApiCarsParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by make
 */
make?: string;
};

export type GetApiCars200 = {
  items?: CarListItem[];
  total?: number;
  page?: number;
  limit?: number;
};

export type GetApiCarsFilters200BrandsWithModels = {[key: string]: string[]};

export type GetApiCarsFilters200 = {
  brandsWithModels?: GetApiCarsFilters200BrandsWithModels;
  regions?: Region[];
  colors?: Color[];
  showrooms?: Showroom[];
};

export type GetApiCarsSearchParams = {
/**
 * Model id or name (partial match)
 */
model?: string;
/**
 * Brand id or name (partial match)
 */
brand?: string;
priceMin?: number;
priceMax?: number;
yearMin?: number;
yearMax?: number;
fuel?: Fuel;
transmission?: Transmission;
page?: number;
limit?: number;
};

export type GetApiCarsSearch200 = {
  items?: CarListItem[];
  total?: number;
  page?: number;
  limit?: number;
};

export type DeleteApiCarsId200 = {
  message?: string;
  deletedCount?: number;
};

export type PostApiCarsDeleteBatchBody = {
  ids?: string[];
};

export type PostApiCarsDeleteBatch200 = {
  deletedIds?: string[];
  deletedCount?: number;
  baseKeys?: string[];
};

export type PostApiCarsCreateBatch201ResultsItem = { [key: string]: unknown };

export type PostApiCarsCreateBatch201 = {
  createdCount?: number;
  results?: PostApiCarsCreateBatch201ResultsItem[];
};

export type GetApiModelsParams = {
page?: number;
limit?: number;
brandId?: string;
};

export type GetApiModels200 = {
  models?: Model[];
  total?: number;
  counts?: number;
  page?: number;
  limit?: number;
};

export type PutApiModelsIdBody = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get all brands (paginated)
 */
export const getApiBrands = (
    params?: GetApiBrandsParams,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<GetApiBrands200>(
      {url: `/api/brands`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiBrandsQueryKey = (params?: GetApiBrandsParams,) => {
    return [
    `/api/brands`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiBrandsQueryOptions = <TData = Awaited<ReturnType<typeof getApiBrands>>, TError = unknown>(params?: GetApiBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrands>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBrandsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBrands>>> = ({ signal }) => getApiBrands(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBrands>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBrandsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBrands>>>
export type GetApiBrandsQueryError = unknown


export function useGetApiBrands<TData = Awaited<ReturnType<typeof getApiBrands>>, TError = unknown>(
 params: undefined |  GetApiBrandsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrands>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBrands>>,
          TError,
          Awaited<ReturnType<typeof getApiBrands>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBrands<TData = Awaited<ReturnType<typeof getApiBrands>>, TError = unknown>(
 params?: GetApiBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrands>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBrands>>,
          TError,
          Awaited<ReturnType<typeof getApiBrands>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBrands<TData = Awaited<ReturnType<typeof getApiBrands>>, TError = unknown>(
 params?: GetApiBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrands>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all brands (paginated)
 */

export function useGetApiBrands<TData = Awaited<ReturnType<typeof getApiBrands>>, TError = unknown>(
 params?: GetApiBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrands>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBrandsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create a brand
 */
export const postApiBrands = (
    brandCreate: BrandCreate,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<Brand>(
      {url: `/api/brands`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: brandCreate, signal
    },
      options);
    }
  


export const getPostApiBrandsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBrands>>, TError,{data: BrandCreate}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBrands>>, TError,{data: BrandCreate}, TContext> => {

const mutationKey = ['postApiBrands'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBrands>>, {data: BrandCreate}> = (props) => {
          const {data} = props ?? {};

          return  postApiBrands(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiBrandsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBrands>>>
    export type PostApiBrandsMutationBody = BrandCreate
    export type PostApiBrandsMutationError = unknown

    /**
 * @summary Create a brand
 */
export const usePostApiBrands = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBrands>>, TError,{data: BrandCreate}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiBrands>>,
        TError,
        {data: BrandCreate},
        TContext
      > => {

      const mutationOptions = getPostApiBrandsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get brand by id
 */
export const getApiBrandsId = (
    id: string,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<Brand>(
      {url: `/api/brands/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiBrandsIdQueryKey = (id?: string,) => {
    return [
    `/api/brands/${id}`
    ] as const;
    }

    
export const getGetApiBrandsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiBrandsId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrandsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBrandsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBrandsId>>> = ({ signal }) => getApiBrandsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBrandsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBrandsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBrandsId>>>
export type GetApiBrandsIdQueryError = unknown


export function useGetApiBrandsId<TData = Awaited<ReturnType<typeof getApiBrandsId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrandsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBrandsId>>,
          TError,
          Awaited<ReturnType<typeof getApiBrandsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBrandsId<TData = Awaited<ReturnType<typeof getApiBrandsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrandsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBrandsId>>,
          TError,
          Awaited<ReturnType<typeof getApiBrandsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBrandsId<TData = Awaited<ReturnType<typeof getApiBrandsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrandsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get brand by id
 */

export function useGetApiBrandsId<TData = Awaited<ReturnType<typeof getApiBrandsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBrandsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBrandsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update a brand
 */
export const putApiBrandsId = (
    id: string,
    brandCreate: BrandCreate,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<Brand>(
      {url: `/api/brands/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: brandCreate
    },
      options);
    }
  


export const getPutApiBrandsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiBrandsId>>, TError,{id: string;data: BrandCreate}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiBrandsId>>, TError,{id: string;data: BrandCreate}, TContext> => {

const mutationKey = ['putApiBrandsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiBrandsId>>, {id: string;data: BrandCreate}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiBrandsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiBrandsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiBrandsId>>>
    export type PutApiBrandsIdMutationBody = BrandCreate
    export type PutApiBrandsIdMutationError = unknown

    /**
 * @summary Update a brand
 */
export const usePutApiBrandsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiBrandsId>>, TError,{id: string;data: BrandCreate}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiBrandsId>>,
        TError,
        {id: string;data: BrandCreate},
        TContext
      > => {

      const mutationOptions = getPutApiBrandsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a brand
 */
export const deleteApiBrandsId = (
    id: string,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<DeleteApiBrandsId200>(
      {url: `/api/brands/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiBrandsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBrandsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiBrandsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiBrandsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiBrandsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiBrandsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiBrandsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiBrandsId>>>
    
    export type DeleteApiBrandsIdMutationError = unknown

    /**
 * @summary Delete a brand
 */
export const useDeleteApiBrandsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBrandsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiBrandsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiBrandsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get images for a car
 */
export const getApiCarImagesCarId = (
    carId: string,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<CarImage[]>(
      {url: `/api/carImages/${carId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiCarImagesCarIdQueryKey = (carId?: string,) => {
    return [
    `/api/carImages/${carId}`
    ] as const;
    }

    
export const getGetApiCarImagesCarIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError = unknown>(carId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCarImagesCarIdQueryKey(carId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCarImagesCarId>>> = ({ signal }) => getApiCarImagesCarId(carId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(carId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCarImagesCarIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCarImagesCarId>>>
export type GetApiCarImagesCarIdQueryError = unknown


export function useGetApiCarImagesCarId<TData = Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError = unknown>(
 carId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarImagesCarId>>,
          TError,
          Awaited<ReturnType<typeof getApiCarImagesCarId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarImagesCarId<TData = Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError = unknown>(
 carId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarImagesCarId>>,
          TError,
          Awaited<ReturnType<typeof getApiCarImagesCarId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarImagesCarId<TData = Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError = unknown>(
 carId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get images for a car
 */

export function useGetApiCarImagesCarId<TData = Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError = unknown>(
 carId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarImagesCarId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCarImagesCarIdQueryOptions(carId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Upload images for a car
 */
export const postApiCarImagesCarIdUpload = (
    carId: string,
    postApiCarImagesCarIdUploadBody: PostApiCarImagesCarIdUploadBody,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
if(postApiCarImagesCarIdUploadBody.images !== undefined) {
 postApiCarImagesCarIdUploadBody.images.forEach(value => formData.append(`images`, value));
 }
if(postApiCarImagesCarIdUploadBody.primaryIndex !== undefined) {
 formData.append(`primaryIndex`, postApiCarImagesCarIdUploadBody.primaryIndex.toString())
 }

      return mutator<PostApiCarImagesCarIdUpload201>(
      {url: `/api/carImages/${carId}/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getPostApiCarImagesCarIdUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCarImagesCarIdUpload>>, TError,{carId: string;data: PostApiCarImagesCarIdUploadBody}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCarImagesCarIdUpload>>, TError,{carId: string;data: PostApiCarImagesCarIdUploadBody}, TContext> => {

const mutationKey = ['postApiCarImagesCarIdUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCarImagesCarIdUpload>>, {carId: string;data: PostApiCarImagesCarIdUploadBody}> = (props) => {
          const {carId,data} = props ?? {};

          return  postApiCarImagesCarIdUpload(carId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCarImagesCarIdUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCarImagesCarIdUpload>>>
    export type PostApiCarImagesCarIdUploadMutationBody = PostApiCarImagesCarIdUploadBody
    export type PostApiCarImagesCarIdUploadMutationError = unknown

    /**
 * @summary Upload images for a car
 */
export const usePostApiCarImagesCarIdUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCarImagesCarIdUpload>>, TError,{carId: string;data: PostApiCarImagesCarIdUploadBody}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCarImagesCarIdUpload>>,
        TError,
        {carId: string;data: PostApiCarImagesCarIdUploadBody},
        TContext
      > => {

      const mutationOptions = getPostApiCarImagesCarIdUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a car image
 */
export const deleteApiCarImagesImageId = (
    imageId: string,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<DeleteApiCarImagesImageId200>(
      {url: `/api/carImages/${imageId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiCarImagesImageIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCarImagesImageId>>, TError,{imageId: string}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCarImagesImageId>>, TError,{imageId: string}, TContext> => {

const mutationKey = ['deleteApiCarImagesImageId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCarImagesImageId>>, {imageId: string}> = (props) => {
          const {imageId} = props ?? {};

          return  deleteApiCarImagesImageId(imageId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCarImagesImageIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCarImagesImageId>>>
    
    export type DeleteApiCarImagesImageIdMutationError = unknown

    /**
 * @summary Delete a car image
 */
export const useDeleteApiCarImagesImageId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCarImagesImageId>>, TError,{imageId: string}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCarImagesImageId>>,
        TError,
        {imageId: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiCarImagesImageIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Set an image as primary
 */
export const patchApiCarImagesImageIdSetPrimary = (
    imageId: string,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<PatchApiCarImagesImageIdSetPrimary200>(
      {url: `/api/carImages/${imageId}/set-primary`, method: 'PATCH'
    },
      options);
    }
  


export const getPatchApiCarImagesImageIdSetPrimaryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCarImagesImageIdSetPrimary>>, TError,{imageId: string}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiCarImagesImageIdSetPrimary>>, TError,{imageId: string}, TContext> => {

const mutationKey = ['patchApiCarImagesImageIdSetPrimary'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiCarImagesImageIdSetPrimary>>, {imageId: string}> = (props) => {
          const {imageId} = props ?? {};

          return  patchApiCarImagesImageIdSetPrimary(imageId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiCarImagesImageIdSetPrimaryMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiCarImagesImageIdSetPrimary>>>
    
    export type PatchApiCarImagesImageIdSetPrimaryMutationError = unknown

    /**
 * @summary Set an image as primary
 */
export const usePatchApiCarImagesImageIdSetPrimary = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCarImagesImageIdSetPrimary>>, TError,{imageId: string}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiCarImagesImageIdSetPrimary>>,
        TError,
        {imageId: string},
        TContext
      > => {

      const mutationOptions = getPatchApiCarImagesImageIdSetPrimaryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Replace an image
 */
export const patchApiCarImagesImageIdReplace = (
    imageId: string,
    patchApiCarImagesImageIdReplaceBody: PatchApiCarImagesImageIdReplaceBody,
 options?: SecondParameter<typeof mutator>,) => {
      
      const formData = new FormData();
if(patchApiCarImagesImageIdReplaceBody.image !== undefined) {
 formData.append(`image`, patchApiCarImagesImageIdReplaceBody.image)
 }

      return mutator<PatchApiCarImagesImageIdReplace200>(
      {url: `/api/carImages/${imageId}/replace`, method: 'PATCH',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getPatchApiCarImagesImageIdReplaceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCarImagesImageIdReplace>>, TError,{imageId: string;data: PatchApiCarImagesImageIdReplaceBody}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiCarImagesImageIdReplace>>, TError,{imageId: string;data: PatchApiCarImagesImageIdReplaceBody}, TContext> => {

const mutationKey = ['patchApiCarImagesImageIdReplace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiCarImagesImageIdReplace>>, {imageId: string;data: PatchApiCarImagesImageIdReplaceBody}> = (props) => {
          const {imageId,data} = props ?? {};

          return  patchApiCarImagesImageIdReplace(imageId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiCarImagesImageIdReplaceMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiCarImagesImageIdReplace>>>
    export type PatchApiCarImagesImageIdReplaceMutationBody = PatchApiCarImagesImageIdReplaceBody
    export type PatchApiCarImagesImageIdReplaceMutationError = unknown

    /**
 * @summary Replace an image
 */
export const usePatchApiCarImagesImageIdReplace = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCarImagesImageIdReplace>>, TError,{imageId: string;data: PatchApiCarImagesImageIdReplaceBody}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiCarImagesImageIdReplace>>,
        TError,
        {imageId: string;data: PatchApiCarImagesImageIdReplaceBody},
        TContext
      > => {

      const mutationOptions = getPatchApiCarImagesImageIdReplaceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get all cars (paginated)
 */
export const getApiCars = (
    params?: GetApiCarsParams,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<GetApiCars200>(
      {url: `/api/cars`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiCarsQueryKey = (params?: GetApiCarsParams,) => {
    return [
    `/api/cars`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCarsQueryOptions = <TData = Awaited<ReturnType<typeof getApiCars>>, TError = unknown>(params?: GetApiCarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCars>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCarsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCars>>> = ({ signal }) => getApiCars(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCars>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCarsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCars>>>
export type GetApiCarsQueryError = unknown


export function useGetApiCars<TData = Awaited<ReturnType<typeof getApiCars>>, TError = unknown>(
 params: undefined |  GetApiCarsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCars>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCars>>,
          TError,
          Awaited<ReturnType<typeof getApiCars>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCars<TData = Awaited<ReturnType<typeof getApiCars>>, TError = unknown>(
 params?: GetApiCarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCars>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCars>>,
          TError,
          Awaited<ReturnType<typeof getApiCars>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCars<TData = Awaited<ReturnType<typeof getApiCars>>, TError = unknown>(
 params?: GetApiCarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCars>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all cars (paginated)
 */

export function useGetApiCars<TData = Awaited<ReturnType<typeof getApiCars>>, TError = unknown>(
 params?: GetApiCarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCars>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCarsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create a new car
 */
export const postApiCars = (
    carCreate: CarCreate,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<Car>(
      {url: `/api/cars`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: carCreate, signal
    },
      options);
    }
  


export const getPostApiCarsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCars>>, TError,{data: CarCreate}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCars>>, TError,{data: CarCreate}, TContext> => {

const mutationKey = ['postApiCars'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCars>>, {data: CarCreate}> = (props) => {
          const {data} = props ?? {};

          return  postApiCars(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCarsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCars>>>
    export type PostApiCarsMutationBody = CarCreate
    export type PostApiCarsMutationError = unknown

    /**
 * @summary Create a new car
 */
export const usePostApiCars = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCars>>, TError,{data: CarCreate}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCars>>,
        TError,
        {data: CarCreate},
        TContext
      > => {

      const mutationOptions = getPostApiCarsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get car filters (brandsWithModels, regions, colors, showrooms)
 */
export const getApiCarsFilters = (
    
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<GetApiCarsFilters200>(
      {url: `/api/cars/filters`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiCarsFiltersQueryKey = () => {
    return [
    `/api/cars/filters`
    ] as const;
    }

    
export const getGetApiCarsFiltersQueryOptions = <TData = Awaited<ReturnType<typeof getApiCarsFilters>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsFilters>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCarsFiltersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCarsFilters>>> = ({ signal }) => getApiCarsFilters(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCarsFilters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCarsFiltersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCarsFilters>>>
export type GetApiCarsFiltersQueryError = unknown


export function useGetApiCarsFilters<TData = Awaited<ReturnType<typeof getApiCarsFilters>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsFilters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarsFilters>>,
          TError,
          Awaited<ReturnType<typeof getApiCarsFilters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarsFilters<TData = Awaited<ReturnType<typeof getApiCarsFilters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsFilters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarsFilters>>,
          TError,
          Awaited<ReturnType<typeof getApiCarsFilters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarsFilters<TData = Awaited<ReturnType<typeof getApiCarsFilters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsFilters>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get car filters (brandsWithModels, regions, colors, showrooms)
 */

export function useGetApiCarsFilters<TData = Awaited<ReturnType<typeof getApiCarsFilters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsFilters>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCarsFiltersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Search cars using filters (model, brand, price range, year range, fuel, transmission)
 */
export const getApiCarsSearch = (
    params?: GetApiCarsSearchParams,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<GetApiCarsSearch200>(
      {url: `/api/cars/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiCarsSearchQueryKey = (params?: GetApiCarsSearchParams,) => {
    return [
    `/api/cars/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiCarsSearchQueryOptions = <TData = Awaited<ReturnType<typeof getApiCarsSearch>>, TError = unknown>(params?: GetApiCarsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsSearch>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCarsSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCarsSearch>>> = ({ signal }) => getApiCarsSearch(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCarsSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCarsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCarsSearch>>>
export type GetApiCarsSearchQueryError = unknown


export function useGetApiCarsSearch<TData = Awaited<ReturnType<typeof getApiCarsSearch>>, TError = unknown>(
 params: undefined |  GetApiCarsSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiCarsSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarsSearch<TData = Awaited<ReturnType<typeof getApiCarsSearch>>, TError = unknown>(
 params?: GetApiCarsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiCarsSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarsSearch<TData = Awaited<ReturnType<typeof getApiCarsSearch>>, TError = unknown>(
 params?: GetApiCarsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsSearch>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search cars using filters (model, brand, price range, year range, fuel, transmission)
 */

export function useGetApiCarsSearch<TData = Awaited<ReturnType<typeof getApiCarsSearch>>, TError = unknown>(
 params?: GetApiCarsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsSearch>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCarsSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get a car by id
 */
export const getApiCarsId = (
    id: string,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<Car>(
      {url: `/api/cars/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiCarsIdQueryKey = (id?: string,) => {
    return [
    `/api/cars/${id}`
    ] as const;
    }

    
export const getGetApiCarsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiCarsId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiCarsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiCarsId>>> = ({ signal }) => getApiCarsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiCarsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiCarsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiCarsId>>>
export type GetApiCarsIdQueryError = unknown


export function useGetApiCarsId<TData = Awaited<ReturnType<typeof getApiCarsId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarsId>>,
          TError,
          Awaited<ReturnType<typeof getApiCarsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarsId<TData = Awaited<ReturnType<typeof getApiCarsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiCarsId>>,
          TError,
          Awaited<ReturnType<typeof getApiCarsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiCarsId<TData = Awaited<ReturnType<typeof getApiCarsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a car by id
 */

export function useGetApiCarsId<TData = Awaited<ReturnType<typeof getApiCarsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiCarsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiCarsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update a car
 */
export const patchApiCarsId = (
    id: string,
    carUpdate: CarUpdate,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<Car>(
      {url: `/api/cars/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: carUpdate
    },
      options);
    }
  


export const getPatchApiCarsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCarsId>>, TError,{id: string;data: CarUpdate}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiCarsId>>, TError,{id: string;data: CarUpdate}, TContext> => {

const mutationKey = ['patchApiCarsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiCarsId>>, {id: string;data: CarUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  patchApiCarsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiCarsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiCarsId>>>
    export type PatchApiCarsIdMutationBody = CarUpdate
    export type PatchApiCarsIdMutationError = unknown

    /**
 * @summary Update a car
 */
export const usePatchApiCarsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiCarsId>>, TError,{id: string;data: CarUpdate}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiCarsId>>,
        TError,
        {id: string;data: CarUpdate},
        TContext
      > => {

      const mutationOptions = getPatchApiCarsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a car
 */
export const deleteApiCarsId = (
    id: string,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<DeleteApiCarsId200>(
      {url: `/api/cars/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiCarsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCarsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiCarsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiCarsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiCarsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiCarsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiCarsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiCarsId>>>
    
    export type DeleteApiCarsIdMutationError = unknown

    /**
 * @summary Delete a car
 */
export const useDeleteApiCarsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiCarsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiCarsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiCarsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete multiple cars
 */
export const postApiCarsDeleteBatch = (
    postApiCarsDeleteBatchBody: PostApiCarsDeleteBatchBody,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<PostApiCarsDeleteBatch200>(
      {url: `/api/cars/delete-batch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiCarsDeleteBatchBody, signal
    },
      options);
    }
  


export const getPostApiCarsDeleteBatchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCarsDeleteBatch>>, TError,{data: PostApiCarsDeleteBatchBody}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCarsDeleteBatch>>, TError,{data: PostApiCarsDeleteBatchBody}, TContext> => {

const mutationKey = ['postApiCarsDeleteBatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCarsDeleteBatch>>, {data: PostApiCarsDeleteBatchBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiCarsDeleteBatch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCarsDeleteBatchMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCarsDeleteBatch>>>
    export type PostApiCarsDeleteBatchMutationBody = PostApiCarsDeleteBatchBody
    export type PostApiCarsDeleteBatchMutationError = unknown

    /**
 * @summary Delete multiple cars
 */
export const usePostApiCarsDeleteBatch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCarsDeleteBatch>>, TError,{data: PostApiCarsDeleteBatchBody}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCarsDeleteBatch>>,
        TError,
        {data: PostApiCarsDeleteBatchBody},
        TContext
      > => {

      const mutationOptions = getPostApiCarsDeleteBatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Create multiple cars in bulk (up to 50)
 */
export const postApiCarsCreateBatch = (
    carsCreateBatch: CarsCreateBatch,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<PostApiCarsCreateBatch201>(
      {url: `/api/cars/create-batch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: carsCreateBatch, signal
    },
      options);
    }
  


export const getPostApiCarsCreateBatchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCarsCreateBatch>>, TError,{data: CarsCreateBatch}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCarsCreateBatch>>, TError,{data: CarsCreateBatch}, TContext> => {

const mutationKey = ['postApiCarsCreateBatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCarsCreateBatch>>, {data: CarsCreateBatch}> = (props) => {
          const {data} = props ?? {};

          return  postApiCarsCreateBatch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiCarsCreateBatchMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCarsCreateBatch>>>
    export type PostApiCarsCreateBatchMutationBody = CarsCreateBatch
    export type PostApiCarsCreateBatchMutationError = unknown

    /**
 * @summary Create multiple cars in bulk (up to 50)
 */
export const usePostApiCarsCreateBatch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCarsCreateBatch>>, TError,{data: CarsCreateBatch}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCarsCreateBatch>>,
        TError,
        {data: CarsCreateBatch},
        TContext
      > => {

      const mutationOptions = getPostApiCarsCreateBatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Health check
 */
export const getApiHealthHealth = (
    
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<void>(
      {url: `/api/health/health`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiHealthHealthQueryKey = () => {
    return [
    `/api/health/health`
    ] as const;
    }

    
export const getGetApiHealthHealthQueryOptions = <TData = Awaited<ReturnType<typeof getApiHealthHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthHealth>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiHealthHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiHealthHealth>>> = ({ signal }) => getApiHealthHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiHealthHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiHealthHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiHealthHealth>>>
export type GetApiHealthHealthQueryError = unknown


export function useGetApiHealthHealth<TData = Awaited<ReturnType<typeof getApiHealthHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealthHealth<TData = Awaited<ReturnType<typeof getApiHealthHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthHealth>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiHealthHealth<TData = Awaited<ReturnType<typeof getApiHealthHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthHealth>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useGetApiHealthHealth<TData = Awaited<ReturnType<typeof getApiHealthHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiHealthHealth>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiHealthHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all models (paginated)
 */
export const getApiModels = (
    params?: GetApiModelsParams,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<GetApiModels200>(
      {url: `/api/models`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiModelsQueryKey = (params?: GetApiModelsParams,) => {
    return [
    `/api/models`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiModelsQueryOptions = <TData = Awaited<ReturnType<typeof getApiModels>>, TError = unknown>(params?: GetApiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModels>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiModelsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiModels>>> = ({ signal }) => getApiModels(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiModelsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiModels>>>
export type GetApiModelsQueryError = unknown


export function useGetApiModels<TData = Awaited<ReturnType<typeof getApiModels>>, TError = unknown>(
 params: undefined |  GetApiModelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModels>>,
          TError,
          Awaited<ReturnType<typeof getApiModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModels<TData = Awaited<ReturnType<typeof getApiModels>>, TError = unknown>(
 params?: GetApiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModels>>,
          TError,
          Awaited<ReturnType<typeof getApiModels>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModels<TData = Awaited<ReturnType<typeof getApiModels>>, TError = unknown>(
 params?: GetApiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModels>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all models (paginated)
 */

export function useGetApiModels<TData = Awaited<ReturnType<typeof getApiModels>>, TError = unknown>(
 params?: GetApiModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModels>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiModelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create a model
 */
export const postApiModels = (
    modelCreate: ModelCreate,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<Model>(
      {url: `/api/models`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelCreate, signal
    },
      options);
    }
  


export const getPostApiModelsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiModels>>, TError,{data: ModelCreate}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiModels>>, TError,{data: ModelCreate}, TContext> => {

const mutationKey = ['postApiModels'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiModels>>, {data: ModelCreate}> = (props) => {
          const {data} = props ?? {};

          return  postApiModels(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiModelsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiModels>>>
    export type PostApiModelsMutationBody = ModelCreate
    export type PostApiModelsMutationError = unknown

    /**
 * @summary Create a model
 */
export const usePostApiModels = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiModels>>, TError,{data: ModelCreate}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiModels>>,
        TError,
        {data: ModelCreate},
        TContext
      > => {

      const mutationOptions = getPostApiModelsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get model by id
 */
export const getApiModelsId = (
    id: string,
 options?: SecondParameter<typeof mutator>,signal?: AbortSignal
) => {
      
      
      return mutator<Model>(
      {url: `/api/models/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiModelsIdQueryKey = (id?: string,) => {
    return [
    `/api/models/${id}`
    ] as const;
    }

    
export const getGetApiModelsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiModelsId>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModelsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiModelsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiModelsId>>> = ({ signal }) => getApiModelsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiModelsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiModelsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiModelsId>>>
export type GetApiModelsIdQueryError = unknown


export function useGetApiModelsId<TData = Awaited<ReturnType<typeof getApiModelsId>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModelsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModelsId>>,
          TError,
          Awaited<ReturnType<typeof getApiModelsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModelsId<TData = Awaited<ReturnType<typeof getApiModelsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModelsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiModelsId>>,
          TError,
          Awaited<ReturnType<typeof getApiModelsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiModelsId<TData = Awaited<ReturnType<typeof getApiModelsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModelsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get model by id
 */

export function useGetApiModelsId<TData = Awaited<ReturnType<typeof getApiModelsId>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiModelsId>>, TError, TData>>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiModelsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update a model
 */
export const putApiModelsId = (
    id: string,
    putApiModelsIdBody: PutApiModelsIdBody,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<void>(
      {url: `/api/models/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiModelsIdBody
    },
      options);
    }
  


export const getPutApiModelsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiModelsId>>, TError,{id: string;data: PutApiModelsIdBody}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiModelsId>>, TError,{id: string;data: PutApiModelsIdBody}, TContext> => {

const mutationKey = ['putApiModelsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiModelsId>>, {id: string;data: PutApiModelsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiModelsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiModelsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiModelsId>>>
    export type PutApiModelsIdMutationBody = PutApiModelsIdBody
    export type PutApiModelsIdMutationError = unknown

    /**
 * @summary Update a model
 */
export const usePutApiModelsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiModelsId>>, TError,{id: string;data: PutApiModelsIdBody}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiModelsId>>,
        TError,
        {id: string;data: PutApiModelsIdBody},
        TContext
      > => {

      const mutationOptions = getPutApiModelsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a model
 */
export const deleteApiModelsId = (
    id: string,
 options?: SecondParameter<typeof mutator>,) => {
      
      
      return mutator<void>(
      {url: `/api/models/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiModelsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiModelsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof mutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiModelsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiModelsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiModelsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiModelsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiModelsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiModelsId>>>
    
    export type DeleteApiModelsIdMutationError = unknown

    /**
 * @summary Delete a model
 */
export const useDeleteApiModelsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiModelsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof mutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiModelsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiModelsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
